config/routes.rb
Rails.application.routes.draw do
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy" # make logout call the destroy inside sessiosn controller
  resources :users, except: [:index, :new]
  resources :sessions, except: [:index, :edit, :update, :show, :new, :destroy]

  # resources :tasks - link the 7 actions - index, create, etc. in controller
  resources :tasks do # nesting notes into the tasks
    resources :notes
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "sites#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :task
    validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user

    has_many :notes
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks
    has_secure_password
    
    validates :name, presence: true
    validates :email, format: { with: /@/, message: "Email must contain '@'"}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private 

    def authenticate 
        if !current_user
            redirect_to root_path, alert: "Invalid Request"
        end
    end

    def login(user)
        session[:user_id] = user.id
    end

    def logout
        session[:user_id] = nil
    end

    def current_user
        if @current_user
            @current_user
        elsif session[:user_id] 
            @current_user = User.find session[:user_id]
        end
    end
    helper_method :current_user # allows us to call current user in views 

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate
  before_action :load_task
  before_action :load_note, except: [:index, :new, :create]

  def index
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def update
    if @note.update note_params
      redirect_to task_notes_path(@task), notice: "Note was updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @note.destroy
    redirect_to task_notes_path(@task), alert: "Note was removed"
  end

  def create
    @note = Note.new note_params
    if @task.notes << @note
      redirect_to task_notes_path, notice: "Note created"
    else
        render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  private

  def note_params
    params.require(:note).permit(:title, :body)
  end

  def load_note
    @note = @task.notes.find params[:id]
  end

  def load_task
    @task = current_user.tasks.find params[:task_id] # task_id is getting loading throug hthe url id section: tasks/{id}/notes
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(email: params[:email]).first
    if @user && @user.authenticate(params[:password])
      login(@user)
      redirect_to root_path, notice: "You have logged in successfully"
    else
      redirect_to login_path, alert: "Invalid Email or Password"
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "You have been logged out"
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate
  # before_action :load_task - ensures the load_task method is called before show, edit, update, and destroy actions.
  before_action :load_task, except: [:new, :index, :create]

  def index
    @tasks = current_user.tasks.all # get only the tasks that belong the the current user
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new task_params
    @task.user = current_user
    if @task.save
      redirect_to tasks_path, notice: "Task created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update task_params
      redirect_to tasks_path, notice: "Task was updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, alert: "Task was removed"
  end


  private

  def load_task
    @task = current_user.tasks.find params[:id]
  end

  def task_params
    params.require(:task).permit(:name,:due_date)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: [:new, :create]
  
  def new
    @user = User.new # Creates empy user, then passes to new.html under users for us to get the form ready for user
  end

  def create
    @user = User.new user_params
    if @user.save
      login(@user)
      redirect_to root_path, notice: "You have successfully signed up"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
  def nav_link(text, path)
    active_class = current_page?(path) ? 'active' : ''

    content_tag :li, class: 'nav-item' do
      link_to text, path, class: "nav-link #{active_class}"
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo List</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <!-- BEGIN NAVBAR -->
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand ps-4" href="/">Todo List</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto ms-4">
            <%= nav_link "Home", root_path %>
            <% if current_user %>
              <%= nav_link "Tasks", tasks_path %>
            <% end %>
          </ul>
          <ul class="navbar-nav ms-auto me-4">
            <% if current_user %>
              <%= nav_link "Logout", logout_path %>
            <% else %>
              <%= nav_link "Login", login_path %>
              <%= nav_link "Sign Up", signup_path %>
            <% end %>

          </ul>
        </div>
      </nav>
    <!-- END NAVBAR -->


    <div class="container-fluid text-center d-flex flex-column align-items-center justify-content-center mt-4">
      <!-- BEGIN FLASH MESSAGE -->
      <div id="flash-messages" class="w-75">
        <% flash.each do |name, msg| %>
          <div class="alert <%= name == 'alert' ? 'alert-danger' : 'alert-primary' %> alert-dismissible fade show" role="alert">
            <strong><%= msg %></strong> 
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
      </div>
      <!-- END FLASH MESSAGE -->
      <div class="border border-2 rounded-3 border-dark-subtle p-5 bg-body-secondary" style="--bs-bg-opacity: .2;">
        <%= yield %>
      </div>
    </div>


  </body>
</html>

app/views/notes/_form.html.erb
<%= bootstrap_form_for([@task,@note]) do |f| %>
  <%= f.text_field :title, placeholder: "Title", hide_label: true %>
  <%= f.text_area :body, placeholder: "Body", hide_label: true %>
  <%= f.primary @note.persisted? ? "Update Note" : "Create Note" %>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id(note) %>" class="note">
    <h3><%= note.title %></h3>
    <p><%= note.body %></p>
</div>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<h1>Notes for <%= @task.name %> </h1>

<div class="row row-cols-1 row-cols-md-2 g-3">
    <% @task.notes.each do |note| %>
    <div class="col border border-dark-subtle pt-3 pb-3">
        <%= render note %>
        <%= link_to "Edit", edit_task_note_path(@task,note), class: "btn btn-primary btn-sm mb-1" %>
        <%= button_to "Delete", [@task, note], method: :delete, class: "btn btn-danger btn-sm mb-1", form: {class: "d-inline", data: {turbo_confirm: "Are you sure you want to remove this note?"}} %>
    </div>
    <% end %>
</div>

<%= link_to "Add Note", new_task_note_path(@task), class: "btn btn-primary mt-3" %>
<%= link_to "Back to Tasks", tasks_path, class: "btn btn-primary mt-3" %>

app/views/notes/new.html.erb
<h1>Create Note</h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<h1>Note for <%= @task.name %> </h1>

<%= render @note %>

<%= link_to "Edit", edit_task_note_path(@task,@note), class: "btn btn-primary" %>
<%= link_to "All Notes", task_notes_path(@task), class: "btn btn-primary" %>
<%= button_to "Delete", [@task, @note], method: :delete, class: "btn btn-secondary", form: {data: {turbo_confirm: "Are you sure you want to remove this note?"}} %>

app/views/sites/index.html.erb
<h1>Welcome to your Todo List!</h1>
<p>Manage all your tasks in one place while taking notes</p>
<p>This web application was created using:</p>
<ul class="list-group">
    <a href="https://rubyonrails.org/" class="list-group-item list-group-item-action list-group-item-primary" target="_blank">Ruby on Rails 7</a>
    <a href="https://getbootstrap.com/" class="list-group-item list-group-item-action list-group-item-primary" target="_blank">Bootstrap 5.3</a>
    <a href="https://www.postgresql.org/" class="list-group-item list-group-item-action list-group-item-primary" target="_blank">PostgreSQL</a>
</ul>
<p class="m-4"><i>Created by <a class="link-primary link-underline link-underline-opacity-0 link-underline-opacity-25-hover" href="https://dylanloree.ca" target="_blank">Dylan Loree</a></i></p>

app/views/tasks/_form.html.erb
<%= bootstrap_form_for(@task) do |f| %>
  <%= f.text_field :name, placeholder: "Name", hide_label: true %>
  <%= f.datetime_field :due_date %>
  <%= f.primary @task.persisted? ? "Update Task" : "Create Task" %>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id(task) %>" class="task">
    <p><strong>Task:</strong> <%= task.name %></p>
    <% if task.due_date %>
        <p>Due: <%= task.due_date %></p>
    <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="container mt-2">

    <h1>Tasks</h1>

    <div class="row row-cols-1 row-cols-md-2 g-3">
        <% @tasks.each do |task| %>
        <div class="col border border-dark-subtle pt-3 pb-3">
            <%= render task %> <!-- Will auto look for a task partial -->
            <%= link_to "Notes", task_notes_path(task), class: "btn btn-primary btn-sm mb-1" %> <!-- URL: /tasks/{id}/notes -->
            <%= link_to "Edit", edit_task_path(task), class: "btn btn-secondary btn-sm mb-1" %>
            <%= button_to "Delete", task, method: :delete, class: "btn btn-danger btn-sm mb-1", form: {class: "d-inline", data: {turbo_confirm: "Are you sure you want to remove this task?"}} %>
        </div>
        <% end %>
    </div>

    <p>
        <%= link_to "New Task", new_task_path, class: "btn btn-primary mt-3" %>
    </p>
    
</div>

app/views/tasks/new.html.erb
<h1>Create Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Task</h1>

<%= render @task %>

<%= link_to "Edit", edit_task_path, class: "btn btn-primary" %>
<%= link_to "All Tasks", tasks_path, class: "btn btn-primary" %>
<%= link_to "Notes", task_notes_path(@task), class: "btn btn-primary" %> <!-- URL: /tasks/{id}/notes -->
<%= button_to "Delete", @task, method: :delete, class: "btn btn-secondary", form: {data: {turbo_confirm: "Are you sure you want to remove this task?"}} %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= bootstrap_form_for(@user) do |f| %>
  <%= f.text_field :name, placeholder: "Name", hide_label: true %>
  <%= f.email_field :email, placeholder: "Email", hide_label: true %>
  <%= f.password_field :password, placeholder: "Password", hide_label: true %>
  <%= f.password_field :password_confirmation, label: "Confirm Password", placeholder: "Confirm Password", hide_label: true %>
  <%= f.primary "Sign Up" %>
<% end %>